spark.master                 yarn
spark.submit.deployMode      client
spark.yarn.queue             default
spark.driver.memory          1g
spark.executor.memory        1g
spark.dynamicAllocation.enabled true
spark.hadoop.fs.defaultFS    hdfs://namenode:9820
